### ISSUE TITLE
`osm_cities` notebook fails for some cities

### ISSUE THREAD

**Issue by delhomer** [lgervasoni/urbansprawl#2]
Hi,
There seems to be an issue with `osm_cities` notebook, as the process fails for some cities. As an example, for Paris, I get a
```
ReadTimeout: HTTPConnectionPool(host='overpass-api.de', port=80): Read timed out. (read timeout=180)
```

Plus, some other cities are really long to be addressed. How much time is the processing supposed to be?

**Comment by lgervasoni** [comment]
Hi, thanks for the opened issues !
1) This error is given due to a problem from the Overpass API.
As for now, I've just tested it and it works. 
Hence, when this happens maybe we can catch this type of error and indicate that the problem is related to the API server. Thus, one should try again later.

2) As for the processing time, it's true it takes a long time (particularly for London).
Maybe it would be better to drop the city of London, and include another one (i.e. a smaller city).
As well, we can show the running times for each city, so as to have an idea on the expected time for each one of them.
